# see https://doc.rust-lang.org/stable/clippy/configuration.html
# see https://rust-lang.github.io/rust-clippy/master/index.html#Configuration
arithmetic-side-effects-allowed = [
  "usize",
] # we're never going to overflow something that large
